services:
  cloudcli:
    container_name: ${CONTAINER_NAME:-cloudcli}
    image: ghcr.io/huangyxi/cloudcli:latest
    userns_mode: keep-id:uid=1000,gid=1000
    ports:
      - "${SERVER_PORT:-3001}:3001"
    volumes:
      - ./workspace:/home/node:Z
      - ./claude:/home/node/.claude:Z
      # - ./codex:/home/node/.codex:Z
      # - ./opencode-config:/home/node/.config/opencode:Z
      # - ./opencode-shared:/home/node/.local/share/opencode:Z
      - ./cloudcli-config:/home/node/.cloudcli:Z
      # - ./cloudcli-workspace-scheduled-prompts:/home/node/.cloudcli-workspace-scheduled-prompts:Z


      # https://github.com/shinpr/mcp-local-rag
      # Add `/opt/mcp-local-rag/dist/index.js` with `CACHE_DIR=/opt/models` as MCP
      # npm config set prefix ~/.local
      # npm install --global mcp-local-rag
      # - ~/.local/lib/node_modules/mcp-local-rag:/opt/mcp-local-rag:ro
      # - ~/.local/bin/mcp-local-rag:/usr/local/bin/mcp-local-rag:ro
      # uvx hf download --local-dir ./models --include "*.json" --include "onnx/model_int8.onnx" Xenova/multilingual-e5-small
      # ln -sf model_int8.onnx models/onnx/model.onnx
      # - ./models:/opt/models/Xenova/all-MiniLM-L6-v2:ro

      # https://github.com/microsoft/markitdown/tree/main/packages/markitdown-mcp
      # Add `python3` with args `/opt/markitdown-mcp/bin/markitdown-mcp` end envs `PYTHONPATH=/opt/markitdown-mcp/lib/python3.13/site-packages` as MCP
      # uv tool install --python 3.13 markitdown-mcp
      # - ~/.local/share/uv/tools/markitdown-mcp:/opt/markitdown-mcp:ro
    restart: unless-stopped
